### PR TITLE
Add support for F1->F12 keys

### PR DESCRIPTION
**Pull request by mrpierrot**
Hi ! 
I just bind the F1 to F12 keys. 
More keys are available but these ones missed for me.

### CODE REVIEW

**Comment by nspitko** [comment]
For ranges, we probably want to map whole sections, see the area just below that range:

```
// Add letters
for( ko in 0...26)
	keycode_map[Key.A + ko] = ImGuiKey.A + ko;
```

These should be contiguous, you can map the whole range in with a quick two liner instead of building a giant monolithic array that might need changed when imgui changes their indices (again)

**Comment by mrpierrot** [comment]
It’s ok for me.
I will propose a commit with this change.

**Comment by mrpierrot** [comment]
After checking. There is an issue. 
In ImGuiDrawable.hx, I can easily map F keys like letters but in ImGui.hx, letters are map with 
```
class ImGuiKeyStringExtender {
	static inline public function imKey(s:String): Int {
		var v = 546 + (s.charCodeAt(0) - 'A'.code);
		return v;
	}
}
```
And I don't think I can extends this function with the same logic because of `s.charCodeAt(0)`.
F Keys are two characters keys and have not associate characters. I don't say we can extends imKey function but that could set more complexity than this pull request. 

I could just update ImGuiDrawable.hx, but I feel it's better to keep parallels implementations.

What do you think about it ?

**Comment by nspitko** [comment]
Good catch! 

In that case maybe it makes more sense to just accept your original PR and use ImGuiKey here. 

I'm not sure what your use case is here, but if the PR currently works then I can accept it as-is.

**Comment by mrpierrot** [comment]
Thank you :-)
My usecase is for a shortcuts system. And F2 is the one for rename things (Like VSCode or Windows Explorer)
In fact, I will use also F Keys for play/stop/pause a game. Anyway, I like use F keys like shortcuts :-)

**Pull request merged**
